export const ADD_RECIPES = "ADD_RECIPES"
export const ADD_INGREDIENTS = "ADD_INGREDIENTS"
export const ADD_RESTAURANTS = "ADD_RESTAURANTS"

export const SELECTED_RECIPE = "SELECTED_RECIPE"
export const SELECTED_RESTAURANT = "SELECTED_RESTAURANT"